### ISSUE TITLE
brca_metabric import error

### ISSUE THREAD

**Issue by chaelir** [cBioPortal/datahub#411]
Hi importing brca_metabric to DB 2.6.0 and Portal cbioportal-v1.13.2
incurs following errors:

Reading data from:  /mnt/datahub/public/brca_metabric/data_gene_matrix.txt

ABORTED!
java.lang.RuntimeException: Cannot find genetic profile brca_metabric_mrna in the database.
at org.mskcc.cbio.portal.scripts.ImportGenePanelProfileMap.getProfileIds(ImportGenePanelProfileMap.java:179)
at org.mskcc.cbio.portal.scripts.ImportGenePanelProfileMap.importData(ImportGenePanelProfileMap.java:119)
at org.mskcc.cbio.portal.scripts.ImportGenePanelProfileMap.run(ImportGenePanelProfileMap.java:97)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.ImportGenePanelProfileMap.main(ImportGenePanelProfileMap.java:207)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error occurred during data loading step. Please fix the problem and run this again to make sure study is completely loaded.
Traceback (most recent call last):
  File "/usr/local/bin/metaImport.py", line 118, in <module>
    cbioportalImporter.main(args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 423, in main
    process_directory(jvm_args, study_directory)
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 321, in process_directory
    import_study_data(jvm_args, meta_filename, data_filename, study_meta_dictionary[meta_filename])
  File "/cbioportal/core/src/main/scripts/importer/cbioportalImporter.py", line 131, in import_study_data
    run_java(*args)
  File "/cbioportal/core/src/main/scripts/importer/cbioportal_common.py", line 799, in run_java
    raise RuntimeError('Aborting due to error while executing step.')
RuntimeError: Aborting due to error while executing step.

**Comment by chaelir** [comment]
delete mode 100644 public/brca_metabric/data_gene_matrix.txt
 delete mode 100644 public/brca_metabric/meta_gene_matrix.txt

went through without gene panel data
